name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run Application
      run: python app.py

    - name: Run Tests
      run: python test.py

    - name: Give Permission to Script
      run: chmod +x deploy.sh

    - name: Deploy Application
      run: ./deploy.sh